services:
  backend:
    build: .
    image: vmo-backend
    ports:
      - "4848:22"
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: vmo-scanner
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  db-data:
    driver: local